/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "badgelink.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(badgelink_Packet, badgelink_Packet, 4)


PB_BIND(badgelink_Request, badgelink_Request, 4)


PB_BIND(badgelink_Response, badgelink_Response, 4)


PB_BIND(badgelink_StartAppReq, badgelink_StartAppReq, AUTO)


PB_BIND(badgelink_Chunk, badgelink_Chunk, 4)


PB_BIND(badgelink_FsUsage, badgelink_FsUsage, AUTO)


PB_BIND(badgelink_AppfsMetadata, badgelink_AppfsMetadata, AUTO)


PB_BIND(badgelink_AppfsActionReq, badgelink_AppfsActionReq, AUTO)


PB_BIND(badgelink_AppfsList, badgelink_AppfsList, 2)


PB_BIND(badgelink_AppfsActionResp, badgelink_AppfsActionResp, 2)


PB_BIND(badgelink_FsStat, badgelink_FsStat, AUTO)


PB_BIND(badgelink_FsActionReq, badgelink_FsActionReq, 2)


PB_BIND(badgelink_FsDirent, badgelink_FsDirent, 2)


PB_BIND(badgelink_FsDirentList, badgelink_FsDirentList, 4)


PB_BIND(badgelink_FsActionResp, badgelink_FsActionResp, 4)


PB_BIND(badgelink_NvsValue, badgelink_NvsValue, 4)


PB_BIND(badgelink_NvsEntry, badgelink_NvsEntry, AUTO)


PB_BIND(badgelink_NvsActionReq, badgelink_NvsActionReq, 4)


PB_BIND(badgelink_NvsEntriesList, badgelink_NvsEntriesList, 4)


PB_BIND(badgelink_NvsActionResp, badgelink_NvsActionResp, 4)













