#!/usr/bin/env python3
"""Generate CRC32 lookup table as C header file.

Uses the standard CRC32 polynomial 0xEDB88320 (reflected form of 0x04C11DB7).
This is the same algorithm used by zlib, Python's binascii.crc32, etc.
"""

def generate_crc32_table():
    """Generate 256-entry CRC32 lookup table."""
    poly = 0xEDB88320
    table = []
    for i in range(256):
        crc = i
        for _ in range(8):
            if crc & 1:
                crc = (crc >> 1) ^ poly
            else:
                crc >>= 1
        table.append(crc)
    return table

def main():
    table = generate_crc32_table()

    print("""/*
 * CRC32 lookup table - AUTO-GENERATED by generate_crc32_table.py
 * DO NOT EDIT MANUALLY
 *
 * Polynomial: 0xEDB88320 (reflected form of 0x04C11DB7)
 * Compatible with zlib, Python binascii.crc32, etc.
 */

#ifndef CRC32_TABLE_H
#define CRC32_TABLE_H

#include <stdint.h>

static const uint32_t crc32_table[256] = {""")

    for i in range(0, 256, 6):
        values = table[i:min(i+6, 256)]
        line = "    " + ", ".join(f"0x{v:08X}" for v in values)
        if i + 6 < 256:
            line += ","
        print(line)

    print("""};

#endif /* CRC32_TABLE_H */""")

if __name__ == "__main__":
    main()
